module.exports = {
  rootDir: "./",
  testEnvironment: "node",
  testPathIgnorePatterns: [
    "/node_modules/",
    ".tmp",
    "/e2e/",
    "/integration/",
    ".cache",
    "/build/",
    ".vscode",
    "/apidoc/",
  ],
  testRegex: ".spec.js$",
  verbose: true,
  collectCoverageFrom: [
    "**/*.js",
    "!<rootDir>/api/*/models/*.js",
    "!<rootDir>/*.js",
    "!<rootDir>/extensions/**",
    "<rootDir>/plugins/*/services/*.js",
    "<rootDir>/plugins/*/controllers/*.js",
    "!<rootDir>/plugins/*/models/*.js",
    "!<rootDir>/plugins/*/entities/*/*.js",
  ],
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/plugins/constants/",
    ".tmp",
    "/e2e/",
    "/integration/",
    ".cache",
    "/build/",
    ".vscode",
    "/test/",
  ],
  coverageDirectory: "coverage",
};
