#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo 'Husky - [Commit Msg]:'

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|style|test|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
  echo "Aborting commit. Your commit message format is invalid, look at https://www.conventionalcommits.org/" >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}"; then
  echo "Aborting commit. Your commit message is too long." >&2
  exit 1
fi